source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.6'


gem 'rails', '~> 6.1.4', '>= 6.1.4.4'
gem 'mysql2', '~> 0.5'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rack-cors'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'dotenv-rails' #環境変数を管理する
  gem 'pry-byebug'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

group :production do
  gem 'unicorn' # Nginx追加時にunicornの追加
 end

 
# devise
gem 'devise'
gem 'devise_token_auth'

# Uploader
gem 'carrierwave'
gem 'fog-aws'

# active_storage使用で追加
gem "aws-sdk-s3", "~> 1.116"
