version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3


jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6
    working_directory: ~/fit-wearness/backend
    steps:
      - checkout:
          path: ~/fit-wearness
      - ruby/install-deps
      - run:
          name: Display the value set in context
          command: echo $EMAIL_ADDRESS

  test:
    docker:
      - image: cimg/ruby:2.7.6
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: backend_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      BACKEND_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/fit-wearness/backend
    steps:
      - checkout:
          path: ~/fit-wearness
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec
  deploy:
    docker:
      - image: cimg/ruby:2.7.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          working_directory: backend
          name: cd dir and push docker image
          command: |
            pwd
            ls
            heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: >-
                heroku run bundle exec rake db:migrate
                RAILS_ENV=production -a $HEROKU_APP_NAME


workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build:
          context: env_value
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
