version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  # heroku: circleci/heroku@1.2.3
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-ecs: circleci/aws-ecs@0.0.8


jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6
    working_directory: ~/fit-wearness/backend
    steps:
      - checkout:
          path: ~/fit-wearness
      - ruby/install-deps
      - run:
          name: Display the value set in context
          command: echo $GMAIL_ADDRESS
  test:
    docker:
      - image: cimg/ruby:2.7.6
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: backend_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      BACKEND_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/fit-wearness/backend
    steps:
      - checkout:
          path: ~/fit-wearness
      - ruby/install-deps
      - run:
          name: Display the value set in context
          command: echo $"{GMAIL_ADDRESS}"
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec
  # build-and-push-image:
  #   working_directory: ~/fit-wearness/backend
  #   steps:
  #     - checkout
  #     - aws-ecr/build-and-push-image:
  #         region: AWS_REGION #OK
  #         account-url: AWS_ECR_ACCOUNT_URL #OK
  #         repo: 'fit-wearness_backend' #OK
  #         tag: "${CIRCLE_SHA1}"
  #         path: ./backend/

              
workflows:
  build_and_push_image:
      jobs:
      - build:
          context: env_value
      - test:
          requires:
            - build
          context: env_value  
      - build-and-push-image:
          context: env_value
          region: AWS_REGION #OK
          account-url: AWS_ECR_ACCOUNT_URL #OK
          repo: 'fit-wearness_backend' #OK
          tag: "${CIRCLE_SHA1}"
          path: './backend'
          requires:
            - test # 追加、テストに成功したときだけデプロイ操作に移るようにする
          filters:    # ここを追加
            branches:
              only:
                - main
      # - aws-ecs/deploy-service-update:
      #     requires:
      #         - aws-ecr/build-and-push-image
      #     family: 'fit_v2_task' # タスク名 #OK
      #     cluster-name: 'v2-fit-backend' #OK
      #     service-name: 'v2-fit-wearness' #OK
      #     container-image-name-updates: 'container=fit-wearness_nginx,tag=${CIRCLE_SHA1}' #OK
      #     filters:    # ここを追加
      #         branches:
      #             only:
      #             - main
